language: node_js

node_js:
- stable

notifications:
  slack:
    if: branch = master

cache:
  directories:
    - "node_modules"

install:
- npm install

script:
- npm run clean
- npm run test:unit
- npm run build