language: javascript

branches:
  only:
  - master
  - development_pablo

node_js:
  - "stable"

before_script:
  - npm install
script:
  - npm test

notifications:
  slack: sytw:pYr6S31RtNxYRcci3xL4cxp8
