language: node_js
dist: xenial

node_js:
- stable

sudo: required

notifications:
  slack: sytw:xbLYeJ93mpOR1m6IsQ5VxKVW

addons:
  sonarcloud:
      organization: "sytw2019"
      token:
        secure: "f6e21994f092e66fb19001d62386835acfa24d13"

cache:
  directories:
    - "node_modules"

install:
- npm install

script:
- npm run clean
- npm run test:unit
- npm run build
- sonar-scanner